spring:
  thymeleaf:
    # 关闭thymeleaf缓存
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: sasa
    url: jdbc:mysql://127.0.0.1:3306/seckill?userSSL=false
    hikari:
      # 连接池名称
      pool-name: DateHikariCP
      # 最小连接数
      minimum-idle: 5
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回得连接自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认180000（30分钟）
      max-lifetime: 1800000
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  resources:
    static-locations: classpath:/static/

mybatis-plus:
#  config-location: classpath*:/mapper/*Mpper.xml
  # 配置Mybatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.lzw.seckill.pojo

# 打印sql日志
logging:
  level:
    com.lzw.seckill.maper: debug
